apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: zad5
  name: php-apache
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: php-apache
    kind: Deployment
  minReplicas: 1
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
